server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: ${AZURE_CLIENT_ID}
            client-secret: ${AZURE_CLIENT_SECRET}
            scope: openid,email,profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Azure AD
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0
            user-name-attribute: email

app:
  jwt:
    secret: ${JWT_SECRET:your-256-bit-secret}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000} # 24 hours